name: Selenium Java Architecture Skeleton

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          java-package: jdk
          cache: "maven"

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Selenium Docker Grid setup
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Run the tests
        run: mvn test
